# Generated by Django 3.2.13 on 2022-10-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20221026_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='nome',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
