# Generated by Django 3.2.13 on 2022-10-31 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_reserva_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='email',
        ),
    ]
