# Generated by Django 3.2.13 on 2022-11-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20221103_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=100, null=True, verbose_name='CPF'),
        ),
    ]
